services:
  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: restaurant_user
      DB_PASS: "123456"
      DB_NAME: restaurant
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: restaurant
      MYSQL_USER: restaurant_user
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
   
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -prootpass --silent"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  dbdata:
